## Importing dependencies

In [1]:
import pandas as pd
import numpy as np

## Q1. Pandas version
What's the version of Pandas that you installed?

In [2]:
pd.__version__

'2.2.2'

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")
data.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

## Q2. Records count
How many records are in the dataset?

In [4]:
data.shape[0]

2160

## Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [5]:
len(data['Brand'].unique())

27

## Q4. Missing values
How many columns in the dataset have missing values?

In [6]:
data.isnull().any().sum()

3

## Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [7]:
data[data['Brand'] == 'Dell']['Final Price'].max()

3936.0

## Q6. Median value of Screen
1. Find the median value of Screen column in the dataset.

In [8]:
data['Screen'].median()

15.6

2. Next, calculate the most frequent value of the same Screen column.

In [9]:
data['Screen'].value_counts().head(1)

Screen
15.6    1009
Name: count, dtype: int64

3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

In [10]:
data['Screen'].fillna(15.6)

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

4. Now, calculate the median value of Screen once again.

In [11]:
data['Screen'].median()

15.6

## Q7. Sum of weights
1. Select all the "Innjoo" laptops from the dataset.

In [12]:
Innjoo_laptops = data[data['Brand'] == 'Innjoo']
Innjoo_laptops

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

2. Select only columns RAM, Storage, Screen.

In [13]:
Innjoo_laptops_selected_columns = data[data['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]
Innjoo_laptops_selected_columns

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

3. Get the underlying NumPy array. Let's call it X.

In [14]:
x = Innjoo_laptops_selected_columns.values
x

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [15]:
XTX = x.T @ x
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

5. Compute the inverse of XTX.

In [16]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

In [17]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

In [18]:
w = (XTX_inv @ x.T) @ y

8. What's the sum of all the elements of the result?

In [22]:
w_sum = np.sum(w)
w_sum

91.29988062995496

### Author
victoria 